[project]
name = "rss-bridge"
version = "0.1.0"
description = "Minimalistic RSS content extractor."
readme = "README.md"
dependencies = [
  "fastapi[standard]",
  "newspaper3k",
  "requests",
  "feedparser",
  "feedgen",
  "tqdm",
  "lxml[html-clean]>=6.0.2",
  "readability-lxml>=0.8.4.1",
]
requires-python = ">=3.12"

[dependency-groups]
dev = ["pytest>=9.0.1"]

[build-system]
requires = ["uv_build>=0.9.9,<0.10.0"]
build-backend = "uv_build"
